name: lolisnatcher
description: Booru Client with the ability to batch download Images.
publish_to: none

version: 2.4.0+188 # remember to update the values in constants.dart after changing them here

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ^3.19.2

dependencies:
  flutter:
    sdk: flutter

  alice_lightweight: ^3.5.1
  app_links: ^3.5.1
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.9.2
  chewie: ^1.7.5
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  dynamic_color: ^1.7.0
  external_video_player_launcher: ^0.0.3
  fast_marquee:
    git:
      # url: "https://github.com/hacker1024/fast_marquee.git" # original
      url: "https://github.com/NANI-SORE/fast_marquee.git"
      ref: 828e79014ed5fd73062d6a24db14b6c114ac175b # master - forked to add richtext
  flash: ^3.1.0
  flex_color_picker: ^3.4.0
  flutter_displaymode: ^0.6.0
  flutter_improved_scrolling: ^0.0.3
  flutter_inappwebview: ^6.0.0
  flutter_inner_drawer:
    git:
      url: "https://github.com/NANI-SORE/flutter_inner_drawer.git"
      ref: 781d16e05e987e3873c1f1562465079f10e390e7 # master
  flutter_linkify: ^6.0.0
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  html: ^0.15.4
  huge_listview: ^2.0.11
  image: ^4.1.7
  intl: ^0.19.0
  keyboard_actions: ^4.2.0
  logger_fork: ^1.2.0
  logger_flutter_fork: ^1.3.1
  # local_auth: ^2.1.7
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  photo_view: # ^0.12.0
    # path: "../forks/photo_view"
    git:
      url: "https://github.com/NANI-SORE/photo_view.git"
      ref: 562c040a52c60c4f647dd779197382c23e87cebf # master
  preload_page_view: ^0.2.0
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  share_plus: ^7.2.2 # not used directly, but is part of some deps (i.e. alice)
  sqflite_common_ffi: ^2.3.2+1
  sqflite: ^2.3.0
  statsfl: ^2.3.0
  transparent_image: ^2.0.1
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  vibration: ^1.8.4
  video_player: ^2.8.3 # in android/app/build.gradle exoplayer dependencies are overriden to lower versions to avoid videos not playing on older devices
  waterfall_flow: ^3.0.3
  xml: ^6.5.0



flutter_icons:
  android: true
  image_path: "assets/images/iconFG.png"
  adaptive_icon_background: "assets/images/iconBG.png"
  adaptive_icon_foreground: "assets/images/iconFG.png"



dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/drawer_icon.png
    - assets/images/loading.gif
